name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependências da API
        run: |
          cd apps/api
          npm ci
      - name: Testes API
        run: |
          cd apps/api
          npm test
      - name: Instalar dependências do Web
        run: |
          cd apps/web
          npm ci
      - name: Build & subir containers com Docker Compose
        run: |
          docker compose up -d web
          sleep 10
      - name: Instalar browsers do Playwright
        run: |
          cd apps/web
          npx playwright install --with-deps
      - name: Testes E2E Web
        run: |
          cd apps/web
          npm run test:e2e
      - name: Tear Down Docker Compose
        if: always()
        run: docker compose down
